config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :tickets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all

  # The option with the :destroy, will iterate through the ticket's project and do a delete
  # This means it will destroy each ticket and every callback that a ticket might have associated
  # If there are no callbacks associated, it's faster to do the destroy_all, that does this:
  # DELETE FROM tickets WHERE project_id = :project_id
  # has_many :tickets, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i(show edit update destroy)

  def index
    @projects = Project.all.reverse
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created"
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated."
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = "Project has been deleted."
      redirect_to projects_path
    else
      flash.now[:notice] = "Project has not been deleted correctly."
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # order in the before_action is important, first set the project, then find tickets associated to the project
  before_action :set_project
  before_action :set_ticket, only: %i(show edit update destroy)

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)

    if @ticket.save
      flash[:notice] = "Ticket has been created"
      redirect_to [@project, @ticket] # nice redirect -> i.e. projects/1/tickets/2
    else
      flash.now[:alert] = "Ticket has not been created"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] =  "Ticket has been deleted"

    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title)%>
        <%= yield :title  %>
      <% else %>
        <%= Ticketee %>
      <% end %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Ticketee', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse" aria-controls="collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= "active" if current_page?("/") %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if current_page?('/users/sign_up') %>">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link"%>
        </li>
      </ul>
  </div>

  </nav>


    <% flash.each do |key, message| %>
      <div><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects </h1>
<%= link_to new_project_path  do %>
  New Project
<% end %>

<div class="projects">
  <% @projects.each do |project| %>
    <h2><%= link_to project.name, project %></h2>
    <p><%= project.description %></p>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render "form", project: @project %>

app/views/projects/show.html.erb
<header>
  <h2>Tickets</h2>

  <ul class="actions">
    <li><%= link_to "New Ticket", new_project_ticket_path(@project) %></li>
  </ul>
</header>

<% title(@project.name, "Projects") %>

<h1><%= @project.name %></h1>
  <p><%= @project.description %></p>

<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", project_path(@project), method: :delete, data: {confirm: "Are you sure you want to delete #{@project.name}"}%>

<ul class="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.name, [@project, ticket] %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_with(model: [project, ticket], local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(ticket.errors.count, "error")%> prohibited this project from being saved
      </h2>

      <ul>
        <% ticket.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>

  <%= form.submit %>
<% end %>

app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<div class="ticket">
  <header>
    <h1>
      <%= @project.name %>
    </h1>
  </header>

  <header>
    <h2>
      <%= @ticket.name %>
    </h2>
    <ul class="actions">
      <!-- nice way of using link_to.. this is equivalent to edit_project_ticket_path(@project, @ticket) -->
      <li>
        <%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
      </li>
      <li>
        <%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
            data: {confirm: "Are you sure you want to delete this ticket?"} %>
      </li>

    </ul>

  </header>

  <%= simple_format(@ticket.description) %>
</div>